name: Contacts
form: $/moonwalkerz/contact/models/contact/fields.yaml
modelClass: MoonWalkerz\Contact\Models\Contact
defaultRedirect: moonwalkerz/contact/contact
create:
    redirect: 'moonwalkerz/contact/contacts/update/:id'
    redirectClose: moonwalkerz/contact/contacts
update:
    redirect: moonwalkerz/contact/contacts
    redirectClose: moonwalkerz/contact/contacts
