list: $/moonwalkerz/contact/models/contact/columns.yaml
modelClass: MoonWalkerz\Contact\Models\Contact
title: Contacts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'moonwalkerz/contact/contacts/update/:id'
