name: Subscribers
form: $/moonwalkerz/contact/models/subsciber/fields.yaml
modelClass: Moonwalkerz\Contact\Models\Subsciber
defaultRedirect: moonwalkerz/contact/subscribers
create:
    redirect: 'moonwalkerz/contact/subscribers/update/:id'
    redirectClose: moonwalkerz/contact/subscribers
update:
    redirect: moonwalkerz/contact/subscribers
    redirectClose: moonwalkerz/contact/subscribers
